export const allImagesForChineseDecor = [
    {

        id: 2,
        slug: "chinese-decor",
        name: "chinese-decor-one",
        src: "https://res.cloudinary.com/dnoycjq2q/image/upload/v1752771946/file_00000000119c622fb312aa694ac3275e_eyeit7.png",
        prescription: `Selected for its unique blend of traditional Chinese aesthetics and modern functionality, this door is a perfect choice for those looking to enhance their home's interior with a touch of elegance and cultural richness. Its intricate design and high-quality materials make it a standout piece that not only serves as a functional entryway but also as a statement of style and sophistication.`,
        whyChoose: ["Exceptional Design: Each decor is meticulously crafted with attention to detail, ensuring superior quality and a flawless finish. Experience the difference of a door built to last", `Durable & Long-Lasting: Constructed from high-grade materials [mention examples like: solid wood, engineered wood, fiberglass, steel, etc., or keep generic if product range is too wide], our doors are designed to withstand daily wear and tear, offering years of reliable performance and beauty.`, `Versatile Design Options: From sleek modern lines to classic panel designs, and rustic [barn/farmhouse] styles, our diverse collection offers a door to complement any architectural style and interior decor. Find the perfect fit for your aesthetic vision`, `Enhanced Functionality & Security: Beyond aesthetics, our doors provide robust performance. [If applicable, mention: Featuring solid core construction for better sound insulation and energy efficiency, or pre-bored for standard hardware for easy lock installation, etc.] Many designs offer enhanced security features for your peace of mind.`, `
Easy Installation (or Contractor-Friendly): Designed for straightforward installation, our doors come ready to be fitted into your existing or new doorway. [If applicable, mention: Pre-hung options available for even simpler setup, or standard sizing to fit common door frames.]`, `Ready for Your Personal Touch: Most of our doors come [primed and ready to paint/stain, or in a natural finish], allowing you to customize them to perfectly match your home's color scheme and personal style.`],
        itemsToPrev: [{ name: "Chinese-Decor-Two", prevSrc: "https://res.cloudinary.com/dnoycjq2q/image/upload/v1752771929/file_00000000284061f8ac00b66c24e770b7_loz2mt.png" }, { name: "Chinese-Decor-Three", prevSrc: "https://res.cloudinary.com/dnoycjq2q/image/upload/v1752771918/file_000000006c2c622f9e9037db2106c666_kc2utm.png" }]

    },
    {

        id: 2,
        slug: "chinese-decor",
        name: "chinese-decor-two",
        src: "https://res.cloudinary.com/dnoycjq2q/image/upload/v1752771929/file_00000000284061f8ac00b66c24e770b7_loz2mt.png",
        prescription: `Selected for its unique blend of traditional Chinese aesthetics and modern functionality, this door is a perfect choice for those looking to enhance their home's interior with a touch of elegance and cultural richness. Its intricate design and high-quality materials make it a standout piece that not only serves as a functional entryway but also as a statement of style and sophistication.`,
        whyChoose: ["Exceptional Craftsmanship: Each door is meticulously crafted with attention to detail, ensuring superior quality and a flawless finish. Experience the difference of a door built to last", `Durable & Long-Lasting: Constructed from high-grade materials [mention examples like: solid wood, engineered wood, fiberglass, steel, etc., or keep generic if product range is too wide], our doors are designed to withstand daily wear and tear, offering years of reliable performance and beauty.`, `Versatile Design Options: From sleek modern lines to classic panel designs, and rustic [barn/farmhouse] styles, our diverse collection offers a door to complement any architectural style and interior decor. Find the perfect fit for your aesthetic vision`, `Enhanced Functionality & Security: Beyond aesthetics, our doors provide robust performance. [If applicable, mention: Featuring solid core construction for better sound insulation and energy efficiency, or pre-bored for standard hardware for easy lock installation, etc.] Many designs offer enhanced security features for your peace of mind.`, `
Easy Installation (or Contractor-Friendly): Designed for straightforward installation, our doors come ready to be fitted into your existing or new doorway. [If applicable, mention: Pre-hung options available for even simpler setup, or standard sizing to fit common door frames.]`, `Ready for Your Personal Touch: Most of our doors come [primed and ready to paint/stain, or in a natural finish], allowing you to customize them to perfectly match your home's color scheme and personal style.`],
        itemsToPrev: [{ name: "Chinese-Decor-One", prevSrc: "https://res.cloudinary.com/dnoycjq2q/image/upload/v1752771946/file_00000000119c622fb312aa694ac3275e_eyeit7.png" }, { name: "Chinese-Decor-Three", prevSrc: "https://res.cloudinary.com/dnoycjq2q/image/upload/v1752771918/file_000000006c2c622f9e9037db2106c666_kc2utm.png" }]

    },
    {

        id: 2,
        slug: "chinese-decor",
        name: "chinese-decor-three",
        src: "https://res.cloudinary.com/dnoycjq2q/image/upload/v1752771918/file_000000006c2c622f9e9037db2106c666_kc2utm.png",
        prescription: `Selected for its unique blend of traditional Chinese aesthetics and modern functionality, this door is a perfect choice for those looking to enhance their home's interior with a touch of elegance and cultural richness. Its intricate design and high-quality materials make it a standout piece that not only serves as a functional entryway but also as a statement of style and sophistication.`,
        whyChoose: ["Exceptional Craftsmanship: Each door is meticulously crafted with attention to detail, ensuring superior quality and a flawless finish. Experience the difference of a door built to last", `Durable & Long-Lasting: Constructed from high-grade materials [mention examples like: solid wood, engineered wood, fiberglass, steel, etc., or keep generic if product range is too wide], our doors are designed to withstand daily wear and tear, offering years of reliable performance and beauty.`, `Versatile Design Options: From sleek modern lines to classic panel designs, and rustic [barn/farmhouse] styles, our diverse collection offers a door to complement any architectural style and interior decor. Find the perfect fit for your aesthetic vision`, `Enhanced Functionality & Security: Beyond aesthetics, our doors provide robust performance. [If applicable, mention: Featuring solid core construction for better sound insulation and energy efficiency, or pre-bored for standard hardware for easy lock installation, etc.] Many designs offer enhanced security features for your peace of mind.`, `
Easy Installation (or Contractor-Friendly): Designed for straightforward installation, our doors come ready to be fitted into your existing or new doorway. [If applicable, mention: Pre-hung options available for even simpler setup, or standard sizing to fit common door frames.]`, `Ready for Your Personal Touch: Most of our doors come [primed and ready to paint/stain, or in a natural finish], allowing you to customize them to perfectly match your home's color scheme and personal style.`],
        itemsToPrev: [{ name: "Chinese-Decor-One", prevSrc: "https://res.cloudinary.com/dnoycjq2q/image/upload/v1752771946/file_00000000119c622fb312aa694ac3275e_eyeit7.png" }, { name: "Chinese-Decor-Two", prevSrc: "https://res.cloudinary.com/dnoycjq2q/image/upload/v1752771929/file_00000000284061f8ac00b66c24e770b7_loz2mt.png" }]

    },
]