export const allImagesForTiles = [
    {

        id: 3,
        slug: "italian-decor",
        name: "italian-decor-one",
        src: "https://res.cloudinary.com/dnoycjq2q/image/upload/v1752771940/Italy1_ub7nfm.png",
        prescription: `Italian Design Elegance: Discover the timeless beauty of Italian decor with our exquisite collection of doors. Each piece is a testament to the rich heritage and craftsmanship that Italy is renowned for, bringing a touch of sophistication to your home. Experience the perfect blend of style and functionality with our Italian-inspired doors, designed to elevate your living spaces with their unique charm and character.`,
        whyChoose: ["Exceptional Design: Each decor is meticulously crafted with attention to detail, ensuring superior quality and a flawless finish. Experience the difference of a door built to last", `Durable & Long-Lasting: Constructed from high-grade materials [mention examples like: solid wood, engineered wood, fiberglass, steel, etc., or keep generic if product range is too wide], our doors are designed to withstand daily wear and tear, offering years of reliable performance and beauty.`, `Versatile Design Options: From sleek modern lines to classic panel designs, and rustic [barn/farmhouse] styles, our diverse collection offers a door to complement any architectural style and interior decor. Find the perfect fit for your aesthetic vision`, `Enhanced Functionality & Security: Beyond aesthetics, our doors provide robust performance. [If applicable, mention: Featuring solid core construction for better sound insulation and energy efficiency, or pre-bored for standard hardware for easy lock installation, etc.] Many designs offer enhanced security features for your peace of mind.`, `
Easy Installation (or Contractor-Friendly): Designed for straightforward installation, our doors come ready to be fitted into your existing or new doorway. [If applicable, mention: Pre-hung options available for even simpler setup, or standard sizing to fit common door frames.]`, `Ready for Your Personal Touch: Most of our doors come [primed and ready to paint/stain, or in a natural finish], allowing you to customize them to perfectly match your home's color scheme and personal style.`],
        itemsToPrev: [{ name: "Italian-Decor-Two", prevSrc: "https://res.cloudinary.com/dnoycjq2q/image/upload/v1752771934/Italy4_kuelya.png" }, { name: "Italian-Decor-Three", prevSrc: "https://res.cloudinary.com/dnoycjq2q/image/upload/v1752771932/Italy2_yd99cw.png" }]

    },
    {

        id: 3,
        slug: "italian-decor",
        name: "italian-decor-two",
        src: "https://res.cloudinary.com/dnoycjq2q/image/upload/v1752771934/Italy4_kuelya.png",
        prescription: `Italian Design Elegance: Discover the timeless beauty of Italian decor with our exquisite collection of doors. Each piece is a testament to the rich heritage and craftsmanship that Italy is renowned for, bringing a touch of sophistication to your home. Experience the perfect blend of style and functionality with our Italian-inspired doors, designed to elevate your living spaces with their unique charm and character.`,
        whyChoose: ["Exceptional Craftsmanship: Each door is meticulously crafted with attention to detail, ensuring superior quality and a flawless finish. Experience the difference of a door built to last", `Durable & Long-Lasting: Constructed from high-grade materials [mention examples like: solid wood, engineered wood, fiberglass, steel, etc., or keep generic if product range is too wide], our doors are designed to withstand daily wear and tear, offering years of reliable performance and beauty.`, `Versatile Design Options: From sleek modern lines to classic panel designs, and rustic [barn/farmhouse] styles, our diverse collection offers a door to complement any architectural style and interior decor. Find the perfect fit for your aesthetic vision`, `Enhanced Functionality & Security: Beyond aesthetics, our doors provide robust performance. [If applicable, mention: Featuring solid core construction for better sound insulation and energy efficiency, or pre-bored for standard hardware for easy lock installation, etc.] Many designs offer enhanced security features for your peace of mind.`, `
Easy Installation (or Contractor-Friendly): Designed for straightforward installation, our doors come ready to be fitted into your existing or new doorway. [If applicable, mention: Pre-hung options available for even simpler setup, or standard sizing to fit common door frames.]`, `Ready for Your Personal Touch: Most of our doors come [primed and ready to paint/stain, or in a natural finish], allowing you to customize them to perfectly match your home's color scheme and personal style.`],
        itemsToPrev: [{ name: "Italian-Decor-Three", prevSrc: "https://res.cloudinary.com/dnoycjq2q/image/upload/v1752771932/Italy2_yd99cw.png" }, { name: "Italian-Decor-Four", prevSrc: "https://res.cloudinary.com/dnoycjq2q/image/upload/v1752771913/file_00000000aab861f59fb63a20bdf44a55_pwln1m.png" }]

    },
    {

        id: 3,
        slug: "italian-decor",
        name: "italian-decor-three",
        src: "https://res.cloudinary.com/dnoycjq2q/image/upload/v1752771932/Italy2_yd99cw.png",
        prescription: `Italian Design Elegance: Discover the timeless beauty of Italian decor with our exquisite collection of doors. Each piece is a testament to the rich heritage and craftsmanship that Italy is renowned for, bringing a touch of sophistication to your home. Experience the perfect blend of style and functionality with our Italian-inspired doors, designed to elevate your living spaces with their unique charm and character.`,
        whyChoose: ["Exceptional Craftsmanship: Each door is meticulously crafted with attention to detail, ensuring superior quality and a flawless finish. Experience the difference of a door built to last", `Durable & Long-Lasting: Constructed from high-grade materials [mention examples like: solid wood, engineered wood, fiberglass, steel, etc., or keep generic if product range is too wide], our doors are designed to withstand daily wear and tear, offering years of reliable performance and beauty.`, `Versatile Design Options: From sleek modern lines to classic panel designs, and rustic [barn/farmhouse] styles, our diverse collection offers a door to complement any architectural style and interior decor. Find the perfect fit for your aesthetic vision`, `Enhanced Functionality & Security: Beyond aesthetics, our doors provide robust performance. [If applicable, mention: Featuring solid core construction for better sound insulation and energy efficiency, or pre-bored for standard hardware for easy lock installation, etc.] Many designs offer enhanced security features for your peace of mind.`, `
Easy Installation (or Contractor-Friendly): Designed for straightforward installation, our doors come ready to be fitted into your existing or new doorway. [If applicable, mention: Pre-hung options available for even simpler setup, or standard sizing to fit common door frames.]`, `Ready for Your Personal Touch: Most of our doors come [primed and ready to paint/stain, or in a natural finish], allowing you to customize them to perfectly match your home's color scheme and personal style.`],
        itemsToPrev: [{ name: "Italian-Decor-Four", prevSrc: "https://res.cloudinary.com/dnoycjq2q/image/upload/v1752771913/file_00000000aab861f59fb63a20bdf44a55_pwln1m.png" }, { name: "Italian-Decor-One", prevSrc: "https://res.cloudinary.com/dnoycjq2q/image/upload/v1752772038/T2_dvgxgw.png" }]

    },
    {

        id: 3,
        slug: "italian-decor",
        name: "italian-decor-four",
        src: "https://res.cloudinary.com/dnoycjq2q/image/upload/v1752771913/file_00000000aab861f59fb63a20bdf44a55_pwln1m.png",
        prescription: `Italian Design Elegance: Discover the timeless beauty of Italian decor with our exquisite collection of doors. Each piece is a testament to the rich heritage and craftsmanship that Italy is renowned for, bringing a touch of sophistication to your home. Experience the perfect blend of style and functionality with our Italian-inspired doors, designed to elevate your living spaces with their unique charm and character.`,
        whyChoose: ["Exceptional Craftsmanship: Each door is meticulously crafted with attention to detail, ensuring superior quality and a flawless finish. Experience the difference of a door built to last", `Durable & Long-Lasting: Constructed from high-grade materials [mention examples like: solid wood, engineered wood, fiberglass, steel, etc., or keep generic if product range is too wide], our doors are designed to withstand daily wear and tear, offering years of reliable performance and beauty.`, `Versatile Design Options: From sleek modern lines to classic panel designs, and rustic [barn/farmhouse] styles, our diverse collection offers a door to complement any architectural style and interior decor. Find the perfect fit for your aesthetic vision`, `Enhanced Functionality & Security: Beyond aesthetics, our doors provide robust performance. [If applicable, mention: Featuring solid core construction for better sound insulation and energy efficiency, or pre-bored for standard hardware for easy lock installation, etc.] Many designs offer enhanced security features for your peace of mind.`, `
Easy Installation (or Contractor-Friendly): Designed for straightforward installation, our doors come ready to be fitted into your existing or new doorway. [If applicable, mention: Pre-hung options available for even simpler setup, or standard sizing to fit common door frames.]`, `Ready for Your Personal Touch: Most of our doors come [primed and ready to paint/stain, or in a natural finish], allowing you to customize them to perfectly match your home's color scheme and personal style.`],
        itemsToPrev: [{ name: "Italian-Decor-Three", prevSrc: "https://res.cloudinary.com/dnoycjq2q/image/upload/v1752771932/Italy2_yd99cw.png" }, { name: "Italian-Decor-One", prevSrc: "https://res.cloudinary.com/dnoycjq2q/image/upload/v1752771913/file_00000000aab861f59fb63a20bdf44a55_pwln1m.png" }]

    }
]