export const allImagesForRussianDecor = [
    {

        id: 1,
        slug: "russian-decor",
        name: "russian-decor-one",
        src: "https://res.cloudinary.com/dnoycjq2q/image/upload/v1752772058/v2_srqlek.png",
        prescription: `Every Design Tells a Story! Explore Our Russian Decor Collection. Immerse yourself in the rich heritage and artistry of our Russian decor collection. Each piece is a testament to timeless craftsmanship, designed to bring elegance and character to your home. Whether you're looking for a statement piece or subtle accents, our collection offers a variety of styles to suit your unique taste and decor needs. Discover the perfect blend of tradition and modernity with our exquisite Russian decor items, crafted to transform your living space into a haven of beauty and sophistication.`,
        whyChoose: ["Exceptional Design: Each decor is meticulously crafted with attention to detail, ensuring superior quality and a flawless finish. Experience the difference of a door built to last", `Durable & Long-Lasting: Constructed from high-grade materials [mention examples like: solid wood, engineered wood, fiberglass, steel, etc., or keep generic if product range is too wide], our doors are designed to withstand daily wear and tear, offering years of reliable performance and beauty.`, `Versatile Design Options: From sleek modern lines to classic panel designs, and rustic [barn/farmhouse] styles, our diverse collection offers a door to complement any architectural style and interior decor. Find the perfect fit for your aesthetic vision`, `Enhanced Functionality & Security: Beyond aesthetics, our doors provide robust performance. [If applicable, mention: Featuring solid core construction for better sound insulation and energy efficiency, or pre-bored for standard hardware for easy lock installation, etc.] Many designs offer enhanced security features for your peace of mind.`, `
Easy Installation (or Contractor-Friendly): Designed for straightforward installation, our doors come ready to be fitted into your existing or new doorway. [If applicable, mention: Pre-hung options available for even simpler setup, or standard sizing to fit common door frames.]`, `Ready for Your Personal Touch: Most of our doors come [primed and ready to paint/stain, or in a natural finish], allowing you to customize them to perfectly match your home's color scheme and personal style.`],
        itemsToPrev: [{ name: "Russian-Decor-Two", prevSrc: "https://res.cloudinary.com/dnoycjq2q/image/upload/v1752772031/Russia-06_y7u2jj.jpg" }, { name: "Russian-Decor-Three", prevSrc: "https://res.cloudinary.com/dnoycjq2q/image/upload/v1752772016/R1_fzcmkq.png" }]

    },
    {

        id: 1,
        slug: "russian-decor",
        name: "russian-decor-two",
        src: "https://res.cloudinary.com/dnoycjq2q/image/upload/v1752772016/R1_fzcmkq.png",
        prescription: `Every Design Tells a Story! Explore Our Russian Decor Collection. Immerse yourself in the rich heritage and artistry of our Russian decor collection. Each piece is a testament to timeless craftsmanship, designed to bring elegance and character to your home. Whether you're looking for a statement piece or subtle accents, our collection offers a variety of styles to suit your unique taste`,
        whyChoose: ["Exceptional Craftsmanship: Each door is meticulously crafted with attention to detail, ensuring superior quality and a flawless finish. Experience the difference of a door built to last", `Durable & Long-Lasting: Constructed from high-grade materials [mention examples like: solid wood, engineered wood, fiberglass, steel, etc., or keep generic if product range is too wide], our doors are designed to withstand daily wear and tear, offering years of reliable performance and beauty.`, `Versatile Design Options: From sleek modern lines to classic panel designs, and rustic [barn/farmhouse] styles, our diverse collection offers a door to complement any architectural style and interior decor. Find the perfect fit for your aesthetic vision`, `Enhanced Functionality & Security: Beyond aesthetics, our doors provide robust performance. [If applicable, mention: Featuring solid core construction for better sound insulation and energy efficiency, or pre-bored for standard hardware for easy lock installation, etc.] Many designs offer enhanced security features for your peace of mind.`, `
Easy Installation (or Contractor-Friendly): Designed for straightforward installation, our doors come ready to be fitted into your existing or new doorway. [If applicable, mention: Pre-hung options available for even simpler setup, or standard sizing to fit common door frames.]`, `Ready for Your Personal Touch: Most of our doors come [primed and ready to paint/stain, or in a natural finish], allowing you to customize them to perfectly match your home's color scheme and personal style.`],
        itemsToPrev: [{ name: "Russian-Decor-Three", prevSrc: "https://res.cloudinary.com/dnoycjq2q/image/upload/v1752772016/R1_fzcmkq.png" }, { name: "Russian-Decor-Four", prevSrc: "https://res.cloudinary.com/dnoycjq2q/image/upload/v1752772013/R3_i23dxb.png" }]

    },
    {

        id: 1,
        slug: "russian-decor",
        name: "russian-decor-three",
        src: "https://res.cloudinary.com/dnoycjq2q/image/upload/v1752772016/R1_fzcmkq.png",
        prescription: `Every Design Tells a Story! Explore Our Russian Decor Collection. Immerse yourself in the rich heritage and artistry of our Russian decor collection. Each piece is a testament to timeless craftsmanship, designed to bring elegance and character to your home. Whether you're looking for a statement piece or subtle accents, our collection offers a variety of styles to suit your unique taste`,
        whyChoose: ["Exceptional Craftsmanship: Each door is meticulously crafted with attention to detail, ensuring superior quality and a flawless finish. Experience the difference of a door built to last", `Durable & Long-Lasting: Constructed from high-grade materials [mention examples like: solid wood, engineered wood, fiberglass, steel, etc., or keep generic if product range is too wide], our doors are designed to withstand daily wear and tear, offering years of reliable performance and beauty.`, `Versatile Design Options: From sleek modern lines to classic panel designs, and rustic [barn/farmhouse] styles, our diverse collection offers a door to complement any architectural style and interior decor. Find the perfect fit for your aesthetic vision`, `Enhanced Functionality & Security: Beyond aesthetics, our doors provide robust performance. [If applicable, mention: Featuring solid core construction for better sound insulation and energy efficiency, or pre-bored for standard hardware for easy lock installation, etc.] Many designs offer enhanced security features for your peace of mind.`, `
Easy Installation (or Contractor-Friendly): Designed for straightforward installation, our doors come ready to be fitted into your existing or new doorway. [If applicable, mention: Pre-hung options available for even simpler setup, or standard sizing to fit common door frames.]`, `Ready for Your Personal Touch: Most of our doors come [primed and ready to paint/stain, or in a natural finish], allowing you to customize them to perfectly match your home's color scheme and personal style.`],
        itemsToPrev: [{ name: "Russian-Decor-Four", prevSrc: "https://res.cloudinary.com/dnoycjq2q/image/upload/v1752772013/R3_i23dxb.png" }, { name: "Russian-Decor-Five", prevSrc: "https://res.cloudinary.com/dnoycjq2q/image/upload/v1752772013/R4_kf10un.png" }]

    },
    {

        id: 1,
        slug: "russian-decor",
        name: "russian-decor-four",
        src: "https://res.cloudinary.com/dnoycjq2q/image/upload/v1752772013/R3_i23dxb.png",
        prescription: `Every Design Tells a Story! Explore Our Russian Decor Collection. Immerse yourself in the rich heritage and artistry of our Russian decor collection. Each piece is a testament to timeless craftsmanship, designed to bring elegance and character to your home. Whether you're looking for a statement piece or subtle accents, our collection offers a variety of styles to suit your unique taste`,
        whyChoose: ["Exceptional Craftsmanship: Each door is meticulously crafted with attention to detail, ensuring superior quality and a flawless finish. Experience the difference of a door built to last", `Durable & Long-Lasting: Constructed from high-grade materials [mention examples like: solid wood, engineered wood, fiberglass, steel, etc., or keep generic if product range is too wide], our doors are designed to withstand daily wear and tear, offering years of reliable performance and beauty.`, `Versatile Design Options: From sleek modern lines to classic panel designs, and rustic [barn/farmhouse] styles, our diverse collection offers a door to complement any architectural style and interior decor. Find the perfect fit for your aesthetic vision`, `Enhanced Functionality & Security: Beyond aesthetics, our doors provide robust performance. [If applicable, mention: Featuring solid core construction for better sound insulation and energy efficiency, or pre-bored for standard hardware for easy lock installation, etc.] Many designs offer enhanced security features for your peace of mind.`, `
Easy Installation (or Contractor-Friendly): Designed for straightforward installation, our doors come ready to be fitted into your existing or new doorway. [If applicable, mention: Pre-hung options available for even simpler setup, or standard sizing to fit common door frames.]`, `Ready for Your Personal Touch: Most of our doors come [primed and ready to paint/stain, or in a natural finish], allowing you to customize them to perfectly match your home's color scheme and personal style.`],
        itemsToPrev: [{ name: "Russian-Decor-Five", prevSrc: "https://res.cloudinary.com/dnoycjq2q/image/upload/v1752772013/R4_kf10un.png" }, { name: "Russian-Decor-Six", prevSrc: "https://res.cloudinary.com/dnoycjq2q/image/upload/v1752772010/R2_b5jreh.png" }]

    },
      {

        id: 1,
        slug: "russian-decor",
        name: "russian-decor-five",
        src: "https://res.cloudinary.com/dnoycjq2q/image/upload/v1752772013/R4_kf10un.png",
        prescription: `Every Design Tells a Story! Explore Our Russian Decor Collection. Immerse yourself in the rich heritage and artistry of our Russian decor collection. Each piece is a testament to timeless craftsmanship, designed to bring elegance and character to your home. Whether you're looking for a statement piece or subtle accents, our collection offers a variety of styles to suit your unique taste`,
        whyChoose: ["Exceptional Craftsmanship: Each door is meticulously crafted with attention to detail, ensuring superior quality and a flawless finish. Experience the difference of a door built to last", `Durable & Long-Lasting: Constructed from high-grade materials [mention examples like: solid wood, engineered wood, fiberglass, steel, etc., or keep generic if product range is too wide], our doors are designed to withstand daily wear and tear, offering years of reliable performance and beauty.`, `Versatile Design Options: From sleek modern lines to classic panel designs, and rustic [barn/farmhouse] styles, our diverse collection offers a door to complement any architectural style and interior decor. Find the perfect fit for your aesthetic vision`, `Enhanced Functionality & Security: Beyond aesthetics, our doors provide robust performance. [If applicable, mention: Featuring solid core construction for better sound insulation and energy efficiency, or pre-bored for standard hardware for easy lock installation, etc.] Many designs offer enhanced security features for your peace of mind.`, `
Easy Installation (or Contractor-Friendly): Designed for straightforward installation, our doors come ready to be fitted into your existing or new doorway. [If applicable, mention: Pre-hung options available for even simpler setup, or standard sizing to fit common door frames.]`, `Ready for Your Personal Touch: Most of our doors come [primed and ready to paint/stain, or in a natural finish], allowing you to customize them to perfectly match your home's color scheme and personal style.`],
        itemsToPrev: [{ name: "Russian-Decor-Six", prevSrc: "https://res.cloudinary.com/dnoycjq2q/image/upload/v1752772010/R2_b5jreh.png" }, { name: "Russian-Decor-Four", prevSrc: "https://res.cloudinary.com/dnoycjq2q/image/upload/v1752772013/R3_i23dxb.png" }]

    },
      {

        id: 1,
        slug: "russian-decor",
        name: "russian-decor-six",
        src: "https://res.cloudinary.com/dnoycjq2q/image/upload/v1752772010/R2_b5jreh.png",
        prescription: `Every Design Tells a Story! Explore Our Russian Decor Collection. Immerse yourself in the rich heritage and artistry of our Russian decor collection. Each piece is a testament to timeless craftsmanship, designed to bring elegance and character to your home. Whether you're looking for a statement piece or subtle accents, our collection offers a variety of styles to suit your unique taste`,
        whyChoose: ["Exceptional Craftsmanship: Each door is meticulously crafted with attention to detail, ensuring superior quality and a flawless finish. Experience the difference of a door built to last", `Durable & Long-Lasting: Constructed from high-grade materials [mention examples like: solid wood, engineered wood, fiberglass, steel, etc., or keep generic if product range is too wide], our doors are designed to withstand daily wear and tear, offering years of reliable performance and beauty.`, `Versatile Design Options: From sleek modern lines to classic panel designs, and rustic [barn/farmhouse] styles, our diverse collection offers a door to complement any architectural style and interior decor. Find the perfect fit for your aesthetic vision`, `Enhanced Functionality & Security: Beyond aesthetics, our doors provide robust performance. [If applicable, mention: Featuring solid core construction for better sound insulation and energy efficiency, or pre-bored for standard hardware for easy lock installation, etc.] Many designs offer enhanced security features for your peace of mind.`, `
Easy Installation (or Contractor-Friendly): Designed for straightforward installation, our doors come ready to be fitted into your existing or new doorway. [If applicable, mention: Pre-hung options available for even simpler setup, or standard sizing to fit common door frames.]`, `Ready for Your Personal Touch: Most of our doors come [primed and ready to paint/stain, or in a natural finish], allowing you to customize them to perfectly match your home's color scheme and personal style.`],
        itemsToPrev: [{ name: "Russian-Decor-Five", prevSrc: "https://res.cloudinary.com/dnoycjq2q/image/upload/v1752772013/R4_kf10un.png" }, { name: "Russian-Decor-One", prevSrc: "https://res.cloudinary.com/dnoycjq2q/image/upload/v1752772058/v2_srqlek.png" }]

    }
]